### ISSUE TITLE
Webmail Verknüpfung

### ISSUE THREAD

**Issue by DieLandmineFetzi** [leomaro/G1_PM_unite#11]
Bei Webmail wird man mit einem Klick auf der Überschrift u:nite nicht auf die Startseite zurückgebracht, wie es eigentlich sein sollte und man bleibt stattdessen auf der Webmail Seite.

**Comment by TechnikTobi** [comment]
Wird gleich behoben

**Comment by TechnikTobi** [comment]
Erledigt.
