### ISSUE TITLE
"Wackelnde" Seiteninhalte

### ISSUE THREAD

**Issue by TechnikTobi** [leomaro/G1_PM_unite#15]
Wenn man beispielsweise zwischen Startseite und About Us wechselt, "wackelt" die Webseite horizontal hin und her. Wechselt man allerdings von Webmail zu About Us ist das nicht der Fall. Ich vermute eine Inkonsistenz in der Formatierung der verschiedenen Seiten.

**Comment by JellyJoe13** [comment]
Issue resolved. Navigations-Elemente haben das Wackeln verursacht. Ich dachte zuerst es ist das fehlende About Kasterl aber die Länge des aside war das Problem, anscheinend war die zu kurz. Hab das in den Mainbody integriert.
(Theoretisch existiert das noch als "Formatierungsleiche" unten. Farblos, aber ohne wackelt es wieder :-/ )
