### ISSUE TITLE
Non-Responsiveness Fehler auf der User-Profil Seite

### ISSUE THREAD

**Issue by TechnikTobi** [leomaro/G1_PM_unite#16]
Öffnet man das User Profil auf einem mobilen Endgerät, so stehen Überschriften wie "Persönliche Daten:" (wo übrigens ein Rechtschreibfehler vorhanden ist: Persönliche, nicht Persö**h**nlich) oder "Dokumentendownload:" über den Bildschirmrand hinaus und werden nicht korrekt auf mehrere Zeilen aufgeteilt.

**Comment by JellyJoe13** [comment]
Typo korregiert und die Titel hab ich gekürzt. Wobei bei mir am Handy wurde es nicht abgeschnitten. Wenn es noch immer nicht passt, könntest du mir bitte ein Bild davon schicken, damit ich weiß wo ich noch nachbessern muss?
Edit: Kann es sein, dass die Prüfbreite von dir kleiner als 320px ist? Dann würde ich den Fehler verstehen, aber gibt es so schmale Smartphones? (ist 320px nicht eher klein oder hab ich da ein falsches Gefühl?)

**Comment by TechnikTobi** [comment]
Schaut jetzt besser aus. Prüfbreite beim Erstellen des Issues war (laut Browser-Angabe) 320px (wobei mir das auch ein wenig schmal vorkommt. Vielleicht werden da nicht die "nativen" Pixel sondern irgendwelche "virtuelle" Angaben gemacht?).
