### ISSUE TITLE
Fehler bei about us-Seite

### ISSUE THREAD

**Issue by DieLandmineFetzi** [leomaro/G1_PM_unite#6]
Der Text unter "Was wollen wir erreichen?" fehlt auf der Webseite

**Comment by AppleForTheKing** [comment]
Falls du gemeint hast, dass der Text bei kleineren Bildschirmen (Auflösung < 2000px) vom Footer überlappt wurde, ist das nun im neuen Pull-Request behoben.

**Comment by DieLandmineFetzi** [comment]
Also bei wird der untere Text vom Footer überlappt wenn ich am PC im Vollbildmodus bin, auch mit dem neuen Patch

**Comment by AppleForTheKing** [comment]
![image](https://user-images.githubusercontent.com/29254555/103372514-8501b000-4ad2-11eb-8781-8f754a7b8aaa.png)

Was hat dein Computer denn für eine Auflösung?

Bzw. könntest du mal versuchen den Cache bei dir zu leeren, vielleicht lädt er noch die alten CSS-Dateien?

**Comment by DieLandmineFetzi** [comment]
Ok mittlerweile klappts auch bei mir, hast vermutlich recht mi dem Cache
