### ISSUE TITLE
Mehr Farbe?

### ISSUE THREAD

**Issue by DieLandmineFetzi** [leomaro/G1_PM_unite#9]
Zur Zeit ist unsere Webseite bis auf die Bilder farblos. Sollten wir vielleicht Teile einfärben um das Ganze ansprechender zu gestalten?

**Comment by JellyJoe13** [comment]
Hm, an und für sich ist es so sehr ordentlich und strukturiert... wir könnten allerdings wenn die Seiten soweit fertig sind das Dunkelgrau der Überschrift durch eine andere Farbe ersetzen?

**Comment by leomaro** [comment]
ich verlinke auch hier nochmal das Corporate Design Manual von der Uni Wien. Da sind auch die konkreten Farbcodes drinnen, für die Farben, die die Uni verwendet. Wir können ja das als Orientierung dafür nehmen.
https://intra.univie.ac.at/fileadmin/user_upload/public/CD/UW_CD_Manual_2020_interaktiv.pdf

**Comment by DieLandmineFetzi** [comment]
Farben wurden angepasst
